### ISSUE TITLE
Getting data from the logs

### ISSUE THREAD

**Issue by sandervandegeijn** [BESTSELLER/pyfortianalyzer#1]
Is it in the scope of your project to collect data from the compromised hosts / blocked traffic / UTM overviews in FA? These would be very helpful if you want to expose this data to a SIEM :)

**Comment by RasmusThing** [comment]
The scope for the project is to be open source and for people to contribute with whatever API endpoints they need.
In the newly released version, I've added a custom_request function in case you'd like to use an API endpoint that the module doesn't have a function for yet.

If you already know what data you need from the API, you are more than welcome to submit an PR with the endpoints.
